data: {chrom_path: ../XuData/titration/y_Sample_NucDG_8_ACTTGA.txt, length_dist_path: ../XuData/titration/lengthDist_Sample_NucDG_8_ACTTGA.txt,
  n_chrom: 16, null_path: ../digestion_bias/control_Sample_NucDG_8_ACTTGA/control.csv,
  regions_path: ../XuData/titration/regions_Sample_NucDG_8_ACTTGA.txt, template_path: ../XuData/titration/template_Sample_NucDG_8_ACTTGA.txt}
detection_output: {detected_pattern: results/detected_titration-2_chrom%02d.txt, fdr_pattern: results/threshold_titration-2_chrom%02d.txt}
detection_params: {alpha: 0.001, compute_maxima_only: false, detect_maxima_only: true,
  method_fdr: bh, n_proc: 8, use_bayes_se: true, verbose: 1}
estimation_output: {coef_pattern: results/coef_titration-2_chrom%02d.txt, null_coef_pattern: results/coef_control_titration-2_chrom%02d.txt,
  null_param_pattern: results/params_control_titration-2_chrom%02d.txt, null_se_pattern: results/se_control_titration-2_chrom%02d.txt,
  param_pattern: results/params_titration-2_chrom%02d.txt, se_pattern: results/se_titration-2_chrom%02d.txt}
estimation_params: {block_width: 2000, diag_approx: true, fix_mu: false, fix_sigmasq: false,
  max_iter: 1024, max_mem: 2048, min_iter: 48, timing: true, tol: 1.0e-06, verbose: 1}
mcmc_output: {cluster_pattern: results/mcmc_clusters_titration-2_chrom%02d.txt, detections_pattern: results/mcmc_detections_titration-2_chrom%02d_pm%d.txt,
  null_cluster_pattern: results/mcmc_clusters_control_titration-2_chrom%02d.txt, null_out_pattern: results/mcmc_draws_control_titration-2_chrom%02d.tar,
  null_param_pattern: results/mcmc_params_control_titration-2_chrom%02d.txt, null_summary_pattern: results/mcmc_summaries_control_titration-2_chrom%02d.txt,
  out_pattern: results/mcmc_draws_titration-2_chrom%02d.tar, param_pattern: results/mcmc_params_titration-2_chrom%02d.txt,
  summary_pattern: results/mcmc_summaries_titration-2_chrom%02d.txt}
mcmc_params: {initialize_params_from_em: false, initialize_theta_from_em: false, mcmc_iterations: 2001,
  n_burnin: 201, path_scratch: /scratch/titration-2}
mcmc_summaries: {bp_per_nucleosome: 160.0, cluster_bw: 20.0, cluster_min_spacing: 147,
  cluster_width: 147, concentration_pm: '0,1,2,3', p_detect: 0.7, p_threshold: '0.5,0.33,0.25,0.10,0.05,0.03,0.01',
  path_scratch: /scratch/titration-2, q_sparsity: '0.5,0.6,0.7,0.8,0.9', width_local: 147}
plotting_output: {gene_plot_pattern: plots/gene_titration-2_%s.png, offset_plot_path: plots/offset_titration-2.png,
  spacing_plot_path: plots/histNucleosomeSpacing_titration-2.png}
prior: {a0: 7.0, b0: 10.0, k0: 0.1, mu0: 0}
processing_output: {nucleosome_pattern: postprocess/nucleosomes_titration-2_chrom%02d.txt,
  offset_pattern: postprocess/offsets_titration-2_chrom%02d.txt, separator: ''}
